module.exports = [
  {
    id: 0,
    title: "ddqwdqwdwqd",
    description: "dqwdqwdqwdqwdqwdqwd",
    image_url: null,
    audio_url: null,
    latitude: -3.0551801,
    longitude: -59.9971085,
    ispersonal: false,
    status: null,
    attendant: null,
    createdAt: "2020-09-29T12:51:04.321Z",
    user: {
      id: 1,
      email: "pedroaraujo1952@hotmail.com",
      first_name: "Pedro",
      last_name: "Araujo",
      phonenumber: "(92) 98428-8408",
      cpf: "054.159.892-93",
    },
  },
  {
    id: 1,
    title: "Lorem Ipsum",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec suscipit pellentesque egestas. Maecenas placerat augue sodales odio imperdiet dignissim. Pellentesque dictum iaculis enim sit amet tincidunt.",
    image_url:
      "uploads\\28-09-2020_18-17-40-ea09beba-d430-4540-a575-f9167SmqGTnCZoy4TmJSDn4VvLykzbH8qd82.jpg",
    audio_url: null,
    latitude: -3.0551801,
    longitude: -59.9971085,
    ispersonal: true,
    status: "accepted",
    attendant: null,
    createdAt: "2020-09-28T22:32:24.000Z",
    user: {
      id: 1,
      email: "pedroaraujo1952@hotmail.com",
      first_name: "Pedro",
      last_name: "Araujo",
      phonenumber: "(92) 98428-8408",
      cpf: "054.159.892-93",
    },
  },
  {
    id: 2,
    title: "DataTypes.STRING",
    description: "DataTypes.TEXT",
    image_url: "DataTypes.STRING",
    audio_url: "DataTypes.STRING",
    latitude: "DataTypes.FLOAT",
    longitude: "DataTypes.FLOAT",
    ispersonal: "DataTypes.BOOLEAN",
    user_id: "DataTypes.INTEGER",
    attendant_id: "DataTypes.INTEGER",
    status: "DataTypes.BOOLEAN",
    createdAt: "10/09/20",
  },
  {
    id: 3,
    title: "DataTypes.STRING",
    description: "DataTypes.TEXT",
    image_url: "DataTypes.STRING",
    audio_url: "DataTypes.STRING",
    latitude: "DataTypes.FLOAT",
    longitude: "DataTypes.FLOAT",
    ispersonal: "DataTypes.BOOLEAN",
    user_id: "DataTypes.INTEGER",
    attendant_id: "DataTypes.INTEGER",
    status: "DataTypes.BOOLEAN",
    createdAt: "10/09/20",
  },
  {
    id: 4,
    title: "DataTypes.STRING",
    description: "DataTypes.TEXT",
    image_url: "DataTypes.STRING",
    audio_url: "DataTypes.STRING",
    latitude: "DataTypes.FLOAT",
    longitude: "DataTypes.FLOAT",
    ispersonal: "DataTypes.BOOLEAN",
    user_id: "DataTypes.INTEGER",
    attendant_id: "DataTypes.INTEGER",
    status: "DataTypes.BOOLEAN",
    createdAt: "10/09/20",
  },
  {
    id: 5,
    title: "DataTypes.STRING",
    description: "DataTypes.TEXT",
    image_url: "DataTypes.STRING",
    audio_url: "DataTypes.STRING",
    latitude: "DataTypes.FLOAT",
    longitude: "DataTypes.FLOAT",
    ispersonal: "DataTypes.BOOLEAN",
    user_id: "DataTypes.INTEGER",
    attendant_id: "DataTypes.INTEGER",
    status: "DataTypes.BOOLEAN",
    createdAt: "10/09/20",
  },
  {
    id: 6,
    title: "DataTypes.STRING",
    description: "DataTypes.TEXT",
    image_url: "DataTypes.STRING",
    audio_url: "DataTypes.STRING",
    latitude: "DataTypes.FLOAT",
    longitude: "DataTypes.FLOAT",
    ispersonal: "DataTypes.BOOLEAN",
    user_id: "DataTypes.INTEGER",
    attendant_id: "DataTypes.INTEGER",
    status: "DataTypes.BOOLEAN",
    createdAt: "10/09/20",
  },
  {
    id: 7,
    title: "DataTypes.STRING",
    description: "DataTypes.TEXT",
    image_url: "DataTypes.STRING",
    audio_url: "DataTypes.STRING",
    latitude: "DataTypes.FLOAT",
    longitude: "DataTypes.FLOAT",
    ispersonal: "DataTypes.BOOLEAN",
    user_id: "DataTypes.INTEGER",
    attendant_id: "DataTypes.INTEGER",
    status: "DataTypes.BOOLEAN",
    createdAt: "10/09/20",
  },
];
